### ISSUE TITLE
not working anymore

### ISSUE THREAD

**Issue by YuanzhiBao** [fabriziodemaria/LeetCode_To_GitHub#10]
Opening LeetCode...
Executing login...
Traceback (most recent call last):
  File "import_lc.py", line 128, in <module>
    main(parse_args())
  File "import_lc.py", line 47, in main
    google = driver.find_element_by_link_text('Google')
  File "/Users/Yuanzhibao/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 428, in find_element_by_link_text
    return self.find_element(by=By.LINK_TEXT, value=link_text)
  File "/Users/Yuanzhibao/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
    'value': value})['value']
  File "/Users/Yuanzhibao/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Users/Yuanzhibao/Library/Python/2.7/lib/python/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"link text","selector":"Google"}
  (Session info: chrome=84.0.4147.105)

**Comment by Sabyasachi-Seal** [comment]
check this out: https://github.com/Sabyasachi-Seal/GitCode/
